#include "StdAfx.h"
// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "characterobject.hxx"

// characterobject_t
// 

const characterobject_t::name_type& characterobject_t::
name () const
{
  return this->name_.get ();
}

characterobject_t::name_type& characterobject_t::
name ()
{
  return this->name_.get ();
}

void characterobject_t::
name (const name_type& x)
{
  this->name_.set (x);
}

void characterobject_t::
name (::std::auto_ptr< name_type > x)
{
  this->name_.set (x);
}

const characterobject_t::scriptName_type& characterobject_t::
scriptName () const
{
  return this->scriptName_.get ();
}

characterobject_t::scriptName_type& characterobject_t::
scriptName ()
{
  return this->scriptName_.get ();
}

void characterobject_t::
scriptName (const scriptName_type& x)
{
  this->scriptName_.set (x);
}

void characterobject_t::
scriptName (::std::auto_ptr< scriptName_type > x)
{
  this->scriptName_.set (x);
}

const characterobject_t::type_type& characterobject_t::
type () const
{
  return this->type_.get ();
}

characterobject_t::type_type& characterobject_t::
type ()
{
  return this->type_.get ();
}

void characterobject_t::
type (const type_type& x)
{
  this->type_.set (x);
}

void characterobject_t::
type (::std::auto_ptr< type_type > x)
{
  this->type_.set (x);
}

const characterobject_t::modelFilename_type& characterobject_t::
modelFilename () const
{
  return this->modelFilename_.get ();
}

characterobject_t::modelFilename_type& characterobject_t::
modelFilename ()
{
  return this->modelFilename_.get ();
}

void characterobject_t::
modelFilename (const modelFilename_type& x)
{
  this->modelFilename_.set (x);
}

void characterobject_t::
modelFilename (::std::auto_ptr< modelFilename_type > x)
{
  this->modelFilename_.set (x);
}

const characterobject_t::resourceGroup_type& characterobject_t::
resourceGroup () const
{
  return this->resourceGroup_.get ();
}

characterobject_t::resourceGroup_type& characterobject_t::
resourceGroup ()
{
  return this->resourceGroup_.get ();
}

void characterobject_t::
resourceGroup (const resourceGroup_type& x)
{
  this->resourceGroup_.set (x);
}

void characterobject_t::
resourceGroup (::std::auto_ptr< resourceGroup_type > x)
{
  this->resourceGroup_.set (x);
}

const characterobject_t::position_type& characterobject_t::
position () const
{
  return this->position_.get ();
}

characterobject_t::position_type& characterobject_t::
position ()
{
  return this->position_.get ();
}

void characterobject_t::
position (const position_type& x)
{
  this->position_.set (x);
}

void characterobject_t::
position (::std::auto_ptr< position_type > x)
{
  this->position_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// characterobject_t
//

characterobject_t::
characterobject_t (const name_type& name,
                   const scriptName_type& scriptName,
                   const type_type& type,
                   const modelFilename_type& modelFilename,
                   const resourceGroup_type& resourceGroup,
                   const position_type& position)
: ::xml_schema::type (),
  name_ (name, ::xml_schema::flags (), this),
  scriptName_ (scriptName, ::xml_schema::flags (), this),
  type_ (type, ::xml_schema::flags (), this),
  modelFilename_ (modelFilename, ::xml_schema::flags (), this),
  resourceGroup_ (resourceGroup, ::xml_schema::flags (), this),
  position_ (position, ::xml_schema::flags (), this)
{
}

characterobject_t::
characterobject_t (const characterobject_t& x,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  scriptName_ (x.scriptName_, f, this),
  type_ (x.type_, f, this),
  modelFilename_ (x.modelFilename_, f, this),
  resourceGroup_ (x.resourceGroup_, f, this),
  position_ (x.position_, f, this)
{
}

characterobject_t::
characterobject_t (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f,
                   ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (f, this),
  scriptName_ (f, this),
  type_ (f, this),
  modelFilename_ (f, this),
  resourceGroup_ (f, this),
  position_ (f, this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void characterobject_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (r);
        continue;
      }
    }

    // scriptName
    //
    if (n.name () == "scriptName" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< scriptName_type > r (
        scriptName_traits::create (i, f, this));

      if (!scriptName_.present ())
      {
        this->scriptName_.set (r);
        continue;
      }
    }

    // type
    //
    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< type_type > r (
        type_traits::create (i, f, this));

      if (!type_.present ())
      {
        this->type_.set (r);
        continue;
      }
    }

    // modelFilename
    //
    if (n.name () == "modelFilename" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< modelFilename_type > r (
        modelFilename_traits::create (i, f, this));

      if (!modelFilename_.present ())
      {
        this->modelFilename_.set (r);
        continue;
      }
    }

    // resourceGroup
    //
    if (n.name () == "resourceGroup" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< resourceGroup_type > r (
        resourceGroup_traits::create (i, f, this));

      if (!resourceGroup_.present ())
      {
        this->resourceGroup_.set (r);
        continue;
      }
    }

    // position
    //
    if (n.name () == "position" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< position_type > r (
        position_traits::create (i, f, this));

      if (!position_.present ())
      {
        this->position_.set (r);
        continue;
      }
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "");
  }

  if (!scriptName_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "scriptName",
      "");
  }

  if (!type_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "type",
      "");
  }

  if (!modelFilename_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "modelFilename",
      "");
  }

  if (!resourceGroup_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "resourceGroup",
      "");
  }

  if (!position_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "position",
      "");
  }
}

characterobject_t* characterobject_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class characterobject_t (*this, f, c);
}

characterobject_t::
~characterobject_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::characterobject_t >
characterObject (const ::std::string& u,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (const ::std::string& u,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::characterObject (isrc, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::characterObject (isrc, h, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::characterObject (isrc, h, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::characterObject (isrc, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::characterObject (isrc, h, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::characterObject (isrc, h, f, p);
}

::std::auto_ptr< ::characterobject_t >
characterObject (::xercesc::InputSource& i,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (::xercesc::InputSource& i,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::characterobject_t > r (
    ::characterObject (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::characterobject_t >
characterObject (const ::xercesc::DOMDocument& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

    ::std::auto_ptr< ::characterobject_t > r (
      ::characterObject (
        c, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  const ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "characterObject" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::characterobject_t > r (
      ::xsd::cxx::tree::traits< ::characterobject_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "characterObject",
    "");
}

::std::auto_ptr< ::characterobject_t >
characterObject (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "characterObject" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::characterobject_t > r (
      ::xsd::cxx::tree::traits< ::characterobject_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "characterObject",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

