#include "StdAfx.h"

// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "soundlist.hxx"

// soundInfo_t
// 

const soundInfo_t::name_type& soundInfo_t::
name () const
{
  return this->name_.get ();
}

soundInfo_t::name_type& soundInfo_t::
name ()
{
  return this->name_.get ();
}

void soundInfo_t::
name (const name_type& x)
{
  this->name_.set (x);
}

void soundInfo_t::
name (::std::auto_ptr< name_type > x)
{
  this->name_.set (x);
}

const soundInfo_t::type_type& soundInfo_t::
type () const
{
  return this->type_.get ();
}

soundInfo_t::type_type& soundInfo_t::
type ()
{
  return this->type_.get ();
}

void soundInfo_t::
type (const type_type& x)
{
  this->type_.set (x);
}

const soundInfo_t::is3D_type& soundInfo_t::
is3D () const
{
  return this->is3D_.get ();
}

soundInfo_t::is3D_type& soundInfo_t::
is3D ()
{
  return this->is3D_.get ();
}

void soundInfo_t::
is3D (const is3D_type& x)
{
  this->is3D_.set (x);
}

const soundInfo_t::looping_type& soundInfo_t::
looping () const
{
  return this->looping_.get ();
}

soundInfo_t::looping_type& soundInfo_t::
looping ()
{
  return this->looping_.get ();
}

void soundInfo_t::
looping (const looping_type& x)
{
  this->looping_.set (x);
}

const soundInfo_t::filename_type& soundInfo_t::
filename () const
{
  return this->filename_.get ();
}

soundInfo_t::filename_type& soundInfo_t::
filename ()
{
  return this->filename_.get ();
}

void soundInfo_t::
filename (const filename_type& x)
{
  this->filename_.set (x);
}

void soundInfo_t::
filename (::std::auto_ptr< filename_type > x)
{
  this->filename_.set (x);
}


// soundList_t
// 

const soundList_t::sound_sequence& soundList_t::
sound () const
{
  return this->sound_;
}

soundList_t::sound_sequence& soundList_t::
sound ()
{
  return this->sound_;
}

void soundList_t::
sound (const sound_sequence& s)
{
  this->sound_ = s;
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// soundInfo_t
//

soundInfo_t::
soundInfo_t (const name_type& name,
             const type_type& type,
             const is3D_type& is3D,
             const looping_type& looping,
             const filename_type& filename)
: ::xml_schema::type (),
  name_ (name, ::xml_schema::flags (), this),
  type_ (type, ::xml_schema::flags (), this),
  is3D_ (is3D, ::xml_schema::flags (), this),
  looping_ (looping, ::xml_schema::flags (), this),
  filename_ (filename, ::xml_schema::flags (), this)
{
}

soundInfo_t::
soundInfo_t (const soundInfo_t& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  type_ (x.type_, f, this),
  is3D_ (x.is3D_, f, this),
  looping_ (x.looping_, f, this),
  filename_ (x.filename_, f, this)
{
}

soundInfo_t::
soundInfo_t (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (f, this),
  type_ (f, this),
  is3D_ (f, this),
  looping_ (f, this),
  filename_ (f, this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void soundInfo_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (r);
        continue;
      }
    }

    // type
    //
    if (n.name () == "type" && n.namespace_ ().empty ())
    {
      if (!type_.present ())
      {
        this->type_.set (type_traits::create (i, f, this));
        continue;
      }
    }

    // is3D
    //
    if (n.name () == "is3D" && n.namespace_ ().empty ())
    {
      if (!is3D_.present ())
      {
        this->is3D_.set (is3D_traits::create (i, f, this));
        continue;
      }
    }

    // looping
    //
    if (n.name () == "looping" && n.namespace_ ().empty ())
    {
      if (!looping_.present ())
      {
        this->looping_.set (looping_traits::create (i, f, this));
        continue;
      }
    }

    // filename
    //
    if (n.name () == "filename" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< filename_type > r (
        filename_traits::create (i, f, this));

      if (!filename_.present ())
      {
        this->filename_.set (r);
        continue;
      }
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "");
  }

  if (!type_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "type",
      "");
  }

  if (!is3D_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "is3D",
      "");
  }

  if (!looping_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "looping",
      "");
  }

  if (!filename_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "filename",
      "");
  }
}

soundInfo_t* soundInfo_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class soundInfo_t (*this, f, c);
}

soundInfo_t::
~soundInfo_t ()
{
}

// soundList_t
//

soundList_t::
soundList_t ()
: ::xml_schema::type (),
  sound_ (::xml_schema::flags (), this)
{
}

soundList_t::
soundList_t (const soundList_t& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  sound_ (x.sound_, f, this)
{
}

soundList_t::
soundList_t (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  sound_ (f, this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void soundList_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // sound
    //
    if (n.name () == "sound" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< sound_type > r (
        sound_traits::create (i, f, this));

      this->sound_.push_back (r);
      continue;
    }

    break;
  }
}

soundList_t* soundList_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class soundList_t (*this, f, c);
}

soundList_t::
~soundList_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::soundList_t >
soundList (const ::std::string& u,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (const ::std::string& u,
           ::xml_schema::error_handler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (const ::std::string& u,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::soundList (isrc, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           ::xml_schema::error_handler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::soundList (isrc, h, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::soundList (isrc, h, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           const ::std::string& sid,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::soundList (isrc, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           const ::std::string& sid,
           ::xml_schema::error_handler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::soundList (isrc, h, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::std::istream& is,
           const ::std::string& sid,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::soundList (isrc, h, f, p);
}

::std::auto_ptr< ::soundList_t >
soundList (::xercesc::InputSource& i,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (::xercesc::InputSource& i,
           ::xml_schema::error_handler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (::xercesc::InputSource& i,
           ::xercesc::DOMErrorHandler& h,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::soundList_t > r (
    ::soundList (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::soundList_t >
soundList (const ::xercesc::DOMDocument& d,
           ::xml_schema::flags f,
           const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

    ::std::auto_ptr< ::soundList_t > r (
      ::soundList (
        c, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  const ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "soundList" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::soundList_t > r (
      ::xsd::cxx::tree::traits< ::soundList_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "soundList",
    "");
}

::std::auto_ptr< ::soundList_t >
soundList (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
           ::xml_schema::flags f,
           const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "soundList" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::soundList_t > r (
      ::xsd::cxx::tree::traits< ::soundList_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "soundList",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

